Initial commit of JankStats samples
android/performance-samples pull request #106
Opened 2022-01-12 00:31 UTC by chethaase

2022-01-12 09:56 UTC, wojtek-kalicinski commented
I'd suggest renaming the directory to JankStatsSample to match other samples in this repo, and also editing the root README file to add a link and description of JankStatsSample, similar to the other samples

2022-01-12 09:57 UTC, wojtek-kalicinski requested changes
I'd suggest renaming the directory to JankStatsSample to match other samples in this repo, and also editing the root README file to add a link and description of JankStatsSample, similar to the other samples

2022-01-24 15:40 UTC, mlykotom commented
I will iterate on it later, to add e.g. bindings to various android classes

2022-02-01 14:25 UTC, wojtek-kalicinski approved these changes

2022-02-01 14:25 UTC, wojtek-kalicinski commented on JankStatsSample/README.md
> +Benchmark Sample
s/Benchmark/JankStats/ ?

2022-02-01 14:25 UTC, wojtek-kalicinski commented on JankStatsSample/app/proguard-rules.pro
> +# Add project specific ProGuard rules here.
remove this file if everything's commented?
(and remove from build.gradle if referenced)

2022-02-01 14:58 UTC, merged